
strictness: medium
pylint:
  disable:
    # Unused arguments are often needed to conform to an expected signature.
    - unused-argument
    # Pylint is sometimes quite bad at the type inference necessary for these.
    - unsubscriptable-object
    - unsupported-membership-test
    # This one is too picky (it complains about *args, **kwargs) and errors of
    # this type are trivial to catch with minimal actual testing
    - arguments-differ
    # The _meta attribute on Django model classes is (annoyingly, kinda) part of
    # models' public API
    - protected-access
    # Pylint doesn't seem to be very good at importing things at the moment
    - import-error
